# common
quarkus:
  http:
    port: 8080
  package:
    type: uber-jar
    runner-suffix: -all-${quarkus.profile}
    output-name: demo-quarkus-3
  profile: dev
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      enable: true
    file:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      enable: true
      path: ./log/${quarkus.package.output-name}.log
      rotation:
        file-suffix: .yyyy-MM-dd
        max-file-size: 50M
        max-backup-index: 10
    level: INFO
  infinispan-client:
    hosts: ${cache.host}:11222;${cache.host}:11272;${cache.host}:11322
    username: "infiuser"
    password: "infiuser"
  ## Docker 4 Mac workaround
    client-intelligence: BASIC

cache:
  cluster-name: test-cluster-name
  host: 192.168.2.254
  name: testCache
greeting:
  message: "hello"
# dev
"%dev":
  greeting:
    message: "hello in dev"
# prod
"%prod":
  greeting:
    message: "hello in prod"