# common
quarkus:
  http:
    port: 8080
  package:
    type: uber-jar
    runner-suffix: -all-${quarkus.profile}
    output-name: demo-quarkus-3
  profile: dev
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      enable: true
    file:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      enable: true
      path: ./log/${quarkus.package.output-name}.log
      rotation:
        file-suffix: .yyyy-MM-dd
        max-file-size: 50M
        max-backup-index: 10
    level: INFO
  infinispan-client:
    hosts: ${cache.host}:11222;${cache.host}:11272;${cache.host}:11322
    username: "infiuser"
    password: "infiuser"
  ## Docker 4 Mac workaround
    client-intelligence: BASIC
    cache:
      "testCache":
        configuration: <?xml version="1.0"?>
          <distributed-cache name="testCache" owners="2" mode="SYNC" remote-timeout="17500" statistics="true">
            <encoding media-type="application/x-java-object"/>
              <locking concurrency-level="1000" isolation="REPEATABLE_READ" acquire-timeout="15000" striping="false"/>
            <transaction mode="FULL_XA" locking="PESSIMISTIC"/>
            <expiration lifespan="3600000" max-idle="-1"/>
            <persistence passivation="false">
              <file-store>
                <data path="data"/>
                <index path="index"/>
              </file-store>
            </persistence><state-transfer timeout="60000"/>
          </distributed-cache>

cache:
  cluster-name: test-cluster-name
  host: 192.168.2.254
  name-test: testCache
  name-dist: distCache
greeting:
  message: "hello"
# dev
"%dev":
  greeting:
    message: "hello in dev"
# prod
"%prod":
  greeting:
    message: "hello in prod"